name: Lint

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [16.14.2]

     steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
          
       - name: Test & publish code coverage      
         uses: paambaati/codeclimate-action@v3
         Add Code Climate secret key
       env:
           ADD_CODE_CLIMATE_SECRET_KEY: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
         debug: true
